# Generated by Django 3.1 on 2024-03-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20240320_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
