# Generated by Django 4.2.7 on 2024-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_id_alter_reviewrating_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
