# Generated by Django 3.1 on 2023-04-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230408_0315'),
        ('cart', '0006_auto_20230416_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='variation',
        ),
        migrations.AddField(
            model_name='order_product',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
