# Generated by Django 3.1 on 2023-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230408_0315'),
        ('cart', '0007_auto_20230416_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='variations',
            field=models.ManyToManyField(blank=True, null=True, to='store.Variation'),
        ),
    ]
