# Generated by Django 3.1 on 2024-03-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_order_address_line_2'),
        ('cart', '0011_auto_20240313_0445'),
    ]

    operations = [
    ]
