# Generated by Django 3.1 on 2024-03-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20240307_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
