# Generated by Django 3.1 on 2024-03-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20230416_0744'),
        ('orders', '0006_auto_20240307_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
